CREATE TABLE `oauth2_authorization` (
  `id` varchar(100) NOT NULL COMMENT '主键ID',
  `tenant_id` varchar(64) NOT NULL COMMENT '租户ID',
  `registered_client_id` varchar(100) NOT NULL COMMENT '客户端ID（关联oauth2_registered_client.id）',
  `principal_name` varchar(200) NOT NULL COMMENT '用户标识（sys_user.username）',
  `authorization_grant_type` varchar(100) NOT NULL COMMENT '授权类型',
  `authorized_scopes` varchar(1000) DEFAULT NULL COMMENT '已授权范围',
  `attributes` varchar(4000) DEFAULT NULL COMMENT '附加属性（JSON）',
  `state` varchar(500) DEFAULT NULL COMMENT '状态值',
  `authorization_code_value` varchar(4000) DEFAULT NULL COMMENT '授权码值',
  `authorization_code_issued_at` timestamp NULL DEFAULT NULL COMMENT '授权码颁发时间',
  `authorization_code_expires_at` timestamp NULL DEFAULT NULL COMMENT '授权码过期时间',
  `authorization_code_metadata` varchar(2000) DEFAULT NULL COMMENT '授权码元数据',
  `access_token_value` varchar(4000) DEFAULT NULL COMMENT '访问令牌值',
  `access_token_issued_at` timestamp NULL DEFAULT NULL COMMENT '访问令牌颁发时间',
  `access_token_expires_at` timestamp NULL DEFAULT NULL COMMENT '访问令牌过期时间',
  `access_token_metadata` varchar(2000) DEFAULT NULL COMMENT '访问令牌元数据',
  `access_token_type` varchar(100) DEFAULT NULL COMMENT '访问令牌类型',
  `access_token_scopes` varchar(1000) DEFAULT NULL COMMENT '访问令牌范围',
  `refresh_token_value` varchar(4000) DEFAULT NULL COMMENT '刷新令牌值',
  `refresh_token_issued_at` timestamp NULL DEFAULT NULL COMMENT '刷新令牌颁发时间',
  `refresh_token_expires_at` timestamp NULL DEFAULT NULL COMMENT '刷新令牌过期时间',
  `refresh_token_metadata` varchar(2000) DEFAULT NULL COMMENT '刷新令牌元数据',
  `oidc_id_token_value` varchar(4000) DEFAULT NULL COMMENT 'OIDC ID令牌值',
  `oidc_id_token_issued_at` timestamp NULL DEFAULT NULL COMMENT 'OIDC ID令牌颁发时间',
  `oidc_id_token_expires_at` timestamp NULL DEFAULT NULL COMMENT 'OIDC ID令牌过期时间',
  `oidc_id_token_metadata` varchar(2000) DEFAULT NULL COMMENT 'OIDC ID令牌元数据',
  `oidc_id_token_claims` varchar(2000) DEFAULT NULL COMMENT 'OIDC ID令牌声明',
  `user_code_value` varchar(4000) DEFAULT NULL COMMENT '用户码值',
  `user_code_issued_at` timestamp NULL DEFAULT NULL COMMENT '用户码颁发时间',
  `user_code_expires_at` timestamp NULL DEFAULT NULL COMMENT '用户码过期时间',
  `user_code_metadata` varchar(2000) DEFAULT NULL COMMENT '用户码元数据',
  `device_code_value` varchar(4000) DEFAULT NULL COMMENT '设备码值',
  `device_code_issued_at` timestamp NULL DEFAULT NULL COMMENT '设备码颁发时间',
  `device_code_expires_at` timestamp NULL DEFAULT NULL COMMENT '设备码过期时间',
  `device_code_metadata` varchar(2000) DEFAULT NULL COMMENT '设备码元数据',
  PRIMARY KEY (`id`),
  KEY `idx_authorization_tenant` (`tenant_id`),
  KEY `idx_authorization_client` (`registered_client_id`),
  KEY `idx_authorization_principal` (`principal_name`),
  KEY `idx_access_token` (`access_token_value`),
  KEY `idx_refresh_token` (`refresh_token_value`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='OAuth2授权令牌表';